name: Build and Deploy to Firebase
on: 
  push:
    branches:
      - master
jobs:
  build-adn-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      CI: false
      REACT_APP_FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      REACT_APP_FIREBASE_DOMAIN: ${{ secrets.FIREBASE_DOMAIN }}
      REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      REACT_APP_FIREBASE_SENDER_ID: ${{ secrets.FIREBASE_SENDER_ID }}
      REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      REACT_APP_GMAPAPI_KEY: ${{ secrets.GMAPAPI_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Npm install
        uses: bahmutov/npm-install@v1
      - name: Npm build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
